FROM cosmtrek/air:latest

ARG APPLICATION
ARG HTTP_PORT=80
ARG GRPC_PORT=50001

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY /apps/${APPLICATION} ./apps/${APPLICATION}
COPY /pkg ./pkg

WORKDIR /app/apps/${APPLICATION}

ENV HTTP_PORT=${HTTP_PORT}
ENV GRPC_PORT=${GRPC_PORT}

EXPOSE ${HTTP_PORT}
EXPOSE ${GRPC_PORT}

CMD [ "air", "-c", ".air.toml" ]