FROM cosmtrek/air:latest

ARG APPLICATION

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY /apps/${APPLICATION} ./apps/${APPLICATION}

WORKDIR /app/apps/${APPLICATION}

EXPOSE 8080
EXPOSE 18080 

CMD [ "air", "-c", ".air.toml" ]