services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: pass123
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
  iam:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.dev
      args:
        APPLICATION: iam
    ports:
      - '8000:80'
      - '18000:18080'
    env_file:
      - ./env/iam.env
    volumes:
      - './apps/iam:/app/apps/iam'
    tty: true
    stdin_open: true
    depends_on:
      - postgres
      - redis
  facility:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.dev
      args:
        APPLICATION: facility
    ports:
      - '8001:80'
    env_file:
      - ./env/facility.env
    volumes:
      - './apps/facility:/app/apps/facility'
    tty: true
    stdin_open: true
    depends_on:
      - iam
      - postgres
      - redis
volumes:
  pgdata:
  redis: